### ISSUE TITLE
inlay hints are a visual distractor

### ISSUE THREAD

**Issue by kynnyhsap** [catppuccin/zed#19]
i use catppuccin mocha theme in zed and when i tried to enabled inlay hinds i noticed that they are just a regular white color indistinguishable from variables, which makes it hard to read the code because i can't what what is type annotated manually and what is not

code without inlay hints
<img width="1149" alt="Screenshot 2024-04-30 at 12 13 28" src="https://github.com/catppuccin/zed/assets/30318777/f346423f-b332-4154-8e53-c39241b7586b">

code with inlay hinds
<img width="1314" alt="Screenshot 2024-04-30 at 12 13 33" src="https://github.com/catppuccin/zed/assets/30318777/7b7fd0fc-0b1b-4bb7-aeef-486f83b856cb">

in the intelliji they look like a badge or a faded comment, i prefer the grayish comment style inlay hints.
<img width="987" alt="Screenshot 2024-04-30 at 12 16 18" src="https://github.com/catppuccin/zed/assets/30318777/d9bd95b4-f9a3-42d3-8c25-c29f6319fcc5">

**Comment by tecandrew** [comment]
oh interesting, thanks for submitting this issue. I see it on my end as well: I normally don't enable this feature. 

will investigate how I could fix this. the built in Zed Syntax debug tree doesn't give a hint as to what colors this 😅 

![image](https://github.com/catppuccin/zed/assets/21319730/9ad6435e-63d8-41d2-ae1b-994c3d0f5da8)

**Comment by tecandrew** [comment]
One Dark and Dracula theme seem to have this colored correctly. this should be an easy fix

![image](https://github.com/catppuccin/zed/assets/21319730/6d7cdff5-519b-4d46-88ce-aa3ccff2aa1e)

![image](https://github.com/catppuccin/zed/assets/21319730/bc456ca9-ab9e-4007-b841-dee71ae9ed8c)

**Comment by kynnyhsap** [comment]
sick! thank you @tecandrew !!!
