### ISSUE TITLE
Title bar becomes transparent when Zed is inactive

### ISSUE THREAD

**Issue by lsunsi** [catppuccin/zed#25]
Since last update (0.145.1) this is happening. Zed devs seems to think it's a theming issue, which would make sense.
For reference: https://github.com/zed-industries/zed/issues/15163 and https://github.com/zed-industries/zed/issues/15112

**Comment by tecandrew** [comment]
hmm, yeah this seems like it's Catppuccin theme on this. I recently tried Zed Linux and vaguely remember running into this issue, but thought it was a general X11/Wayland bug

**Comment by tecandrew** [comment]
fixed by #26
