### ISSUE TITLE
macOS no window shadow due to blurry background.

### ISSUE THREAD

**Issue by Congyuwang** [catppuccin/zed#27]
v0.2.9 on macOS, now no window background. This is not good. due to d4990b9

**Comment by Congyuwang** [comment]
<img width="1175" alt="截圖 2024-07-28 17 54 45" src="https://github.com/user-attachments/assets/c59399fa-c14e-4813-900a-97358e0d6557">

**Comment by tecandrew** [comment]
interesting... I didn't notice this initially when testing. definitely a bug, although it seems it may be a **Zed** bug. I see this now when testing _any_ theme using `background.appearance": "blurred"`

Rosé Pine (on white background)

No background blur
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/a211d0f8-c427-4f8f-b209-4d1df7c0a6ed">

With Background Blur
<img width="1236" alt="image" src="https://github.com/user-attachments/assets/8a5dd24e-d4dc-40f1-b593-e9347353fa7f">

**Comment by tecandrew** [comment]
I would have expected drop shadow to work regardless of a "blurred background" setting. I'll rollback if we get enough reports on this

**Comment by tecandrew** [comment]
seems like you may have already explored this area a bit in https://github.com/zed-industries/zed/issues/10993 

i'll reference this in a new issue

**Comment by tecandrew** [comment]
ooh, okay wait this is an issue. needs a rollback for this.

overlapping zed windows without the drop shadow make it fairly hard to distinguish between
<img width="297" alt="image" src="https://github.com/user-attachments/assets/2cd02a0b-d3ae-4a0d-bfa6-80f5bc1d4bc5">
