### ISSUE TITLE
Inlay Hints Color Change in v0.2.12

### ISSUE THREAD

**Issue by daniele-solutiontech** [catppuccin/zed#39]
In v0.2.12, the color of the inlay hints has shifted to a green tone that feels visually unappealing.

Current appearance in v0.2.12:
<img width="907" alt="v0 2 12" src="https://github.com/user-attachments/assets/db35b723-d3da-4713-8684-c0753f51cd58">

For comparison, here is how they appeared in v0.2.11:
<img width="902" alt="v0 2 11" src="https://github.com/user-attachments/assets/69e36727-9c24-4b88-809d-ee74ef949f55">

**Comment by tecandrew** [comment]
I typically don't enable inlay hints personally, but have for the past few days. I agree: doesn't look too nice 😅 I'll rollback.
