### ISSUE TITLE
text selection color makes editor hard to use

### ISSUE THREAD

**Issue by Nolancc** [catppuccin/zed#4]
Hello I have tried to use this theme and it is great but there is one problem that is stopping me from using it. That is the text selection color is so bright that I cannot see the text, and even worse it highlights when I'm typing so it's very hard to see what I am typing. This is a very simple change that will make this theme 100 times more usable
Here is an image of the issue:

![image](https://github.com/catppuccin/zed/assets/152654399/ebd5995e-2f49-45fc-97aa-d391062c0854)

**Comment by tecandrew** [comment]
ahh, i never really found this an issue, but it could be made more similar to VS Code. i
<img width="644" alt="image" src="https://github.com/catppuccin/zed/assets/21319730/d1ed784b-8e35-4107-b267-375705a6ec27">

**Comment by Nolancc** [comment]
thanks, it could also look worse on my display than it is on yours

**Comment by Nolancc** [comment]
should I make a PR?

**Comment by tecandrew** [comment]
no need, it's a straight forward adjustment. i adjusted it to match closer to vscode with a slight transparency. trying to stay within the bounds the Catppuccin coloring scheme 

<img width="1222" alt="image" src="https://github.com/catppuccin/zed/assets/21319730/f6fdb25f-2d14-46e6-9bca-aa3febd3e6fe">

<img width="1148" alt="image" src="https://github.com/catppuccin/zed/assets/21319730/0c2217f3-b2d1-4760-8115-3880f979896b">

<img width="1235" alt="image" src="https://github.com/catppuccin/zed/assets/21319730/26839977-8ee8-42bb-accf-ab3fc74db022">

**Comment by Nolancc** [comment]
thanks
