### ISSUE TITLE
Low contrast between selected and non-selected tabs

### ISSUE THREAD

**Issue by zenkimoto** [catppuccin/zed#41]
Hello, I'v been really enjoying this theme so far.  I love the subtly of the tabs but would it be possible to increase the contrast between the selected tab and the non-selected tabs?  My eyes have difficulty distinguishing which tab is selected and which isn't.  I considered a few ideas either changing the selected tab color or perhaps bolding the selected file name?

**Comment by tecandrew** [comment]
I try to stay close to the vscode colors, but I do see your point: the tabs are sometimes a little too low-contrast on some screens. VS Code has the Catppuccin accent under the _active_ tab and Zed does not.

I'll look into what looks good and visible 👍 

![image](https://github.com/user-attachments/assets/94a8d225-9b48-48b9-97f9-c69fcfadeaf0)
![image](https://github.com/user-attachments/assets/2b8f9bba-11b1-421e-a9c0-4ecd7d56176f)

> or perhaps bolding the selected file name

there's currently not a whole lot of customizability for tabs within Zed: themes could only tweak active and inactive color

**Comment by zenkimoto** [comment]
@tecandrew Thanks so much for making the adjustment and making this awesome Zed theme!

**Comment by sipec** [comment]
In light mode this new tab colors are semantically counter-intuitive. The lighter tab that is closer to the color of the main background is the inactive tab, while the darker tab is the active one. 

![image](https://github.com/user-attachments/assets/33753def-60f7-4c47-9ede-41eb95de8c76)

There have been many cases where I was confused about which tab I was on!

**Comment by tecandrew** [comment]
hmm, idk why I never considered this. it doesn't look a bit better 🤔 I guess I just wanted to stay close to vscode's style.

<img width="1056" alt="image" src="https://github.com/user-attachments/assets/a347e0a8-5eb8-49e0-80f7-89994a47b6d1">

if you'd like to try this @sipec you can add the following in your `settings.json`

Latte
```json
"experimental.theme_overrides": {
  "tab.active_background": "#eff1f5",
  "tab.inactive_background": "#dce0e8"
},
```

Mocha
```json
"experimental.theme_overrides": {
    "tab.inactive_background": "#11111b",
    "tab.active_background": "#1e1e2e"
},
```
