### ISSUE TITLE
Insufficient contrast between selection and highlight

### ISSUE THREAD

**Issue by joeldrapper** [catppuccin/zed#5]
With my eyes, I can’t tell the difference, at a glance, between _selected text_ and highlighted symbols. In this screenshot, for example, the third `node` is selected, while the other four are just highlighted.

<img width="568" alt="Screenshot 2024-03-07 at 10 21 19" src="https://github.com/catppuccin/zed/assets/246692/08d5d8f3-b778-4db2-ad63-12ee933bfc06">

This is particularly confusing when trying to work with multiple cursors.

Here’s a closer look. In this screenshot `opt` is selected, while the rest of the word `options` is just highlighted because it’s the active symbol.

<img width="560" alt="Screenshot 2024-03-07 at 10 25 32" src="https://github.com/catppuccin/zed/assets/246692/cfa7592e-6a73-4b05-9192-0f732850239a">

**Comment by tecandrew** [comment]
@joeldrapper this is a more of a problem with Zed editor itself and have brought this up before 😅 

https://github.com/zed-industries/zed/issues/8316

https://github.com/zed-industries/zed/issues/7448

I found some themes are better at it than others, but it's still low-contrast.

**Comment by joeldrapper** [comment]
Oh that’s interesting. I thought there was a way to specify the selection colour. Some themes have a selection color that's different from the active symbol highlight color.

**Comment by tecandrew** [comment]
Zed has some interesting behaviors with what is affect by tweaking these parameters. I'll see if I could find a good middle ground solution for keeping the Catppuccin colors and adjusting for better standout contrast.

![image](https://github.com/catppuccin/zed/assets/21319730/a94c9b20-a65c-4086-9c33-abb65a4bb934)

I'm finding that VS Code overrides the current auto-select with the "selection highlight" color, while Zed just maintains the `read_background` param and not accommodate for selection color. 
![image](https://github.com/catppuccin/zed/assets/21319730/29af031b-a269-4dc5-9c5c-149770044e2c)

**Comment by tecandrew** [comment]
Zed Ayu Dark (default theme) seems to have a good solution, so I'll replicate this behavior

- auto-selection color is darker player1 selection color 
- "write_background" color is something grey

![image](https://github.com/catppuccin/zed/assets/21319730/32185420-17c9-48fa-85bc-15f73ce736aa)
