### ISSUE TITLE
Full project search filter buttons looks the same when pressed on and off

### ISSUE THREAD

**Issue by valerykh** [catppuccin/zed#53]
Full project search filter buttons looks the same when pressed on and off

* Press cmd+shift+F 
![CleanShot 2024-12-02 at 13 58 33@2x](https://github.com/user-attachments/assets/21066b5c-e98d-4274-93cb-c2104507884d)
All three buttons looks the same when on or off

**Comment by tecandrew** [comment]
thanks for reporting. will look into this
