### ISSUE TITLE
Add option to disable italics on keywords

### ISSUE THREAD

**Issue by ravshansbox** [catppuccin/zed#6]

**Comment by tecandrew** [comment]
currently there is no way to customize a theme within Zed unless you install this as a "dev extension." 😅

is this request just for personal preference or does Italics make it difficult to read within the editor somewhere?

**Comment by ravshansbox** [comment]
This was possible on vscode extension.
Yes, italic keywords make code less readable for some.

**Comment by tecandrew** [comment]
> possible on vscode extension

I'll leave this issue open for the possibility of when Zed makes themes more customizable like VS Code 😄

> Yes, italic keywords make code less readable for some.

I'm planning to define more of Zed's tree-sitter `syntax` styling and coloring. The various italics will be adjusted when this is published

**Comment by tecandrew** [comment]
@ravshansbox found out that there's an experimental feature that **overrides** any theme you set to your own preference using the `~/.config/zed/settings.json` file.

<img width="467" alt="image" src="https://github.com/catppuccin/zed/assets/21319730/f1c98ea2-6711-45c2-a55c-3ff09b8ca222">

you can set the `syntax` sub list to override anything set here https://github.com/catppuccin/zed/blob/f376e3a02606b942566ad56efd3b9b07fefd8375/template.hbr#L167

**Comment by Moshyfawn** [comment]
I think the way it is currently done in Zed is to create a separate theme in the theme family that doesn't use italics. Check out [this example](https://github.com/elGusto/night-owlz/blob/e745179850838aa65d9b1d684b28b80c0bded6b3/themes/NightOwl.json#L811C7-L811C37) of how the Night Owl theme handles it.

**Comment by tecandrew** [comment]
@Moshyfawn though I like this idea, we would essentially generate an additional 4 Themes for _just_ italics/non-italics (and x4 for other variants) like the `Arctis` theme on vscode 
![image](https://github.com/catppuccin/zed/assets/21319730/659d49a1-0a4f-4730-bc8a-3ccdf6b26ee7)

I personally don't like this, but curious on whether anyone else in the Org disagrees? this port is modeled after the [vscode theme](https://github.com/catppuccin/vscode) and it doesn't have these variants 😅 

cc: @sgoudham

**Comment by ravshansbox** [comment]
Separate theme for every combination of options doesn't look good. What if someone asks for a "no bold" option?

**Comment by sgoudham** [comment]
Our VSCode port has a built-in option to enable italics. JetBrains actually does ship non-italics variants under the same plugin so I think it's more than fine. 

Our new whiskers version actually makes generating these variants extremely trivial. I'd check out the matrix option for whiskers v2 in the docs! 

cc: @nullishamy as she's currently going through porting repositories to our new version

**Comment by sgoudham** [comment]
> Separate theme for every combination of options doesn't look good. What if someone asks for a "no bold" option?

I don't mind italic variants since other themes tend to offer these too, however I've never seen non-bold/bold themes shipped as "variants"

I believe I'd that close that type of issue as not planned or, as we've done with this issue, tag it with "currently not possible" or equivalent

**Comment by tecandrew** [comment]
i'll start a PR draft to create the `non-italic` variants. bold and other variants in the future would be GH issue labeled as such 🫡
