### ISSUE TITLE
Add distinct color for object properties

### ISSUE THREAD

**Issue by znycheporuk** [catppuccin/zed#9]
Add distinct color for object properties

Catppuccin Mocha
<img width="372" alt="Screenshot 2024-03-25 at 19 03 09" src="https://github.com/catppuccin/zed/assets/42861377/a733a7d2-9651-464c-ba10-1ae2a4db8df3">
Ayu Dark
<img width="377" alt="Screenshot 2024-03-25 at 19 03 41" src="https://github.com/catppuccin/zed/assets/42861377/03af3acb-8ca7-4cfa-9b34-a0bb18e9eb71">

**Comment by tecandrew** [comment]
what language is this so I could test on my end?

**Comment by znycheporuk** [comment]
That's JavaScript, thanks for your work 🙏
